//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace breweries.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class beer
    {
        public int Id { get; set; }
        public int StyleId { get; set; }
        public int BreweryId { get; set; }
        [Required]
        public string Name { get; set; }
        [DisplayFormat(DataFormatString = "{0:0.0}%"), Range(0, 60)]
        public decimal Strength { get; set; }
        public bool Can { get; set; }
        public bool Bottle { get; set; }
        public bool Keg { get; set; }
        public string Badge { get; set; }
    
        public virtual Brewery Brewery { get; set; }
        public virtual Style Style { get; set; }
    }
}
