//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace breweries.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Brewery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Brewery()
        {
            this.beers = new HashSet<beer>();
        }
    
        public int Id { get; set; }
        [Required]
        [Remote("doesBreweryExist", "BreweriesController", HttpMethod = "POST", ErrorMessage = "This brewery already exists")]
        public string Name { get; set; }
        [Required]
        [MaxLength(10, ErrorMessage = "Please enter a London postcode")]
        public string Location { get; set; }
        public string Website { get; set; }
        public string Logo { get; set; }
        [HiddenInput(DisplayValue = false)]
        public Nullable<decimal> lat { get; set; }
        [HiddenInput(DisplayValue = false)]
        public Nullable<decimal> lon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<beer> beers { get; set; }
    }
}
